[package]
name = "termtrack"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.18.0"
crossterm = {version = "=0.28.1"}
device_query = "2.1.0"
flume = "0.11.0"
futures = "0.3.30"
rayon = "1.10.0"
wgpu = "22.1.0"
